### ISSUE TITLE
Liftoff possibly creating CDS with '.' in phase column?

### ISSUE THREAD

**Issue by GallVp** [Plant-Food-Research-Open/genepal#115]
### Description of the bug

CDS features with '.' in the phase column (8) is not permissible. This might be causing the following error downstream in the pipeline. An issue on the liftoff repo mentions something similar. See: https://github.com/agshumate/Liftoff/issues/67

Command executed:

  tsebra.py \
      -g eriantha_h2.clean.gtf \
      -e hintsfile.gff \
       \
      -c tsebra-config.cfg \
       \
      -o eriantha_h2.gtf \
      -s eriantha_h2.tsv
  
  cat <<-END_VERSIONS > versions.yml
  "PLANTFOODRESEARCHOPEN_GENEPAL:GENEPAL:FASTA_LIFTOFF:GFF_TSEBRA_SPFILTERFEATUREFROMKILLLIST:TSEBRA":
      tsebra: 1.1.2.5
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  ### READING GENE PREDICTION: [eriantha_h2.clean.gtf]
  ### READING EXTRINSIC EVIDENCE: [hintsfile.gff]
  ### BUILD OVERLAP GRAPH
  Traceback (most recent call last):
    File "/usr/local/bin/tsebra.py", line 235, in <module>
      main()
    File "/usr/local/bin/tsebra.py", line 97, in main
      graph.build()
    File "/usr/local/bin/overlap_graph.py", line 185, in build
      if self.compare_tx_cds(tx1, tx2):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/bin/overlap_graph.py", line 207, in compare_tx_cds
      coords += [c + [int(phase)] for phase, coord_phase in tx1.get_type_coords('CDS').items() for c in coord_phase]
                      ^^^^^^^^^^
  ValueError: invalid literal for int() with base 10: '.'

### Command used and terminal output

```console
nextflow run plant-food-research-open/genepal \
--outdir 's3://***' \
-r '0.5.0' \
-params-file params.json \
-c mmc.config \
-resume
```

### System information

plant-food-research-open/genepal 0.5.0

**Comment by GallVp** [comment]
In the reported version `plant-food-research-open/genepal 0.5.0`, this is not possible as GFFREAD is run before and after LIFTOFF. GFFREAD automatically fixes the phase column.
