### ISSUE TITLE
Failure at `tsebra` step

### ISSUE THREAD

**Issue by GallVp** [Plant-Food-Research-Open/genepal#77]
### Description of the bug

```bash
INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
### READING GENE PREDICTION: [ET33_1.clean.gtf]
### READING EXTRINSIC EVIDENCE: [hintsfile.gff]
### BUILD OVERLAP GRAPH
Traceback (most recent call last):
  File "/usr/local/bin/tsebra.py", line 235, in <module>
    main()
  File "/usr/local/bin/tsebra.py", line 97, in main
    graph.build()
  File "/usr/local/bin/overlap_graph.py", line 185, in build
    if self.compare_tx_cds(tx1, tx2):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/overlap_graph.py", line 207, in compare_tx_cds
    coords += [c + [int(phase)] for phase, coord_phase in tx1.get_type_coords('CDS').items() for c in coord_phase]
                    ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '.'
```

### Command used and terminal output

```console
nextflow run plant-food-research-open/genepal -r 0.4.0 \
  -profile singularity \
  --input assemblysheet.csv \
  --rna_evidence samplesheet.csv \
  --liftoff_annotations lift.csv \
  --repeat_annotator edta \
  --skip_fastp True \
  --edta_is_sensitive True \
  --protein_evidence Araport11_pep_20220914.fasta \
  --outdir deneme
```

### System information

plant-food-research-open/genepal -r 0.4.0

**Comment by GallVp** [comment]
Possibly linked to https://github.com/Plant-Food-Research-Open/genepal/issues/115

**Comment by GallVp** [comment]
Possibly linked to https://github.com/Plant-Food-Research-Open/genepal/issues/120

**Comment by GallVp** [comment]
Possibly linked to https://github.com/Plant-Food-Research-Open/genepal/issues/121
